name: Test and Publish Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3.2.0

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build and Test
        run: dotnet test
        
  publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Build and Push the Image
        run : |
          docker login --username ${{ github.actor }} --password ${{ secrets.GH_PT}} ghcr.io
          docker build --tag ghcr.io/wojdak/pl-players-api:latest --build-arg ConnectionStrings__PremierLeagueDatabase="${{secrets.PREMIERLEAGUEDATABASECONNECTION}}"  --build-arg Jwt__Key="${{secrets.JWTKEY}}" --build-arg Jwt__Issuer="${{secrets.JWTISSUER}}" --build-arg Jwt__Audience="${{secrets.JWTAUDIENCE}}" .
          docker push ghcr.io/wojdak/pl-players-api:latest 

  deploy:
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        
      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v3.0.1
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ghcr.io/wojdak/pl-players-api:latest
